name: HaskellNixCabalStarter
version: '0.1.0.0'
author: HaskellNixCabalStarter
maintainer: HaskellNixCabalStarter
license: MIT
dependencies:
- base
- yesod
- yesod-form
- text
- string-conversions
- hspec
- hspec-wai
- yesod-test
executables:
  app:
    source-dirs: src
    main: Main.hs
  test:
    source-dirs: src
    main: Test.hs
default-extensions: 
- LambdaCase
